# Generated by Django 4.2.20 on 2025-05-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_dc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemStatusTable',
            fields=[
                ('itemstatusid', models.AutoField(db_column='itemStatusID', primary_key=True, serialize=False)),
                ('itemstat', models.CharField(db_column='itemStat', max_length=99)),
            ],
            options={
                'db_table': 'item status table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentTable',
            fields=[
                ('paymentid', models.AutoField(db_column='paymentID', primary_key=True, serialize=False)),
                ('mop', models.CharField(db_column='MOP', max_length=99)),
                ('date', models.DateField(db_column='Date')),
                ('time', models.TimeField(db_column='Time')),
            ],
            options={
                'db_table': 'payment_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PaystatTable',
            fields=[
                ('paystatid', models.AutoField(db_column='paystatID', primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=99)),
            ],
            options={
                'db_table': 'paystat_table',
                'managed': False,
            },
        ),
    ]
