# Generated by Django 4.2.20 on 2025-09-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_dc', '0002_itemstatustable_paymenttable_paystattable'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangayTable',
            fields=[
                ('barangay_id', models.IntegerField(primary_key=True, serialize=False)),
                ('barangay_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'barangay_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CityMunicipalityTable',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'city_municipality_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerAddressTable',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('customerid', models.IntegerField(blank=True, db_column='customerID', null=True)),
                ('block_number', models.CharField(blank=True, max_length=50, null=True)),
                ('lot_number', models.CharField(blank=True, max_length=50, null=True)),
                ('house_number', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_number', models.CharField(blank=True, max_length=50, null=True)),
                ('street_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subdivision', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('delivery_instructions', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_address_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProdNameTable',
            fields=[
                ('prodnameid', models.AutoField(db_column='prodNameId', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=999, null=True)),
            ],
            options={
                'db_table': 'prod_name_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProvinceTable',
            fields=[
                ('province_id', models.IntegerField(primary_key=True, serialize=False)),
                ('province_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'province_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegionTable',
            fields=[
                ('region_id', models.IntegerField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'region_table',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='BeigeTable',
        ),
        migrations.DeleteModel(
            name='BlueTable',
        ),
        migrations.DeleteModel(
            name='BrownTable',
        ),
        migrations.DeleteModel(
            name='GrayTable',
        ),
        migrations.DeleteModel(
            name='OrangeTable',
        ),
        migrations.DeleteModel(
            name='RedTable',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.DeleteModel(
            name='WhiteTable',
        ),
        migrations.DeleteModel(
            name='YellowTable',
        ),
        migrations.AlterModelOptions(
            name='paymenttable',
            options={},
        ),
    ]
