# Generated by Django 4.2.20 on 2025-09-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_dc', '0003_barangaytable_citymunicipalitytable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAddressTable',
            fields=[
                ('sales_address_id', models.AutoField(primary_key=True, serialize=False)),
                ('block_number', models.CharField(blank=True, max_length=50, null=True)),
                ('lot_number', models.CharField(blank=True, max_length=50, null=True)),
                ('house_number', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_number', models.CharField(blank=True, max_length=50, null=True)),
                ('street_name', models.CharField(blank=True, max_length=255, null=True)),
                ('subdivision', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('delivery_instructions', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sales_address_table',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='CustomerAddressTable',
        ),
        migrations.AlterModelOptions(
            name='paymenttable',
            options={'managed': False},
        ),
    ]
