# Generated by Django 4.2.20 on 2025-09-25 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_dc', '0005_alter_salestable_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesaddresstable',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='salestable',
            options={'managed': False},
        ),
    ]
