# Generated by Django 3.2 on 2025-10-16 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_dc', '0006_alter_salesaddresstable_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryTable',
            fields=[
                ('countryid', models.AutoField(db_column='countryID', primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=999)),
            ],
            options={
                'db_table': 'country_table',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='salesaddresstable',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='PendingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('order_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social_dc.customertable')),
            ],
            options={
                'db_table': 'pending_order_table',
                'managed': True,
            },
        ),
    ]
