# Generated by Django 4.2.20 on 2025-04-15 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BeigeTable',
            fields=[
                ('beigeid', models.IntegerField(db_column='beigeID', primary_key=True, serialize=False)),
                ('beigeimage', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'beige_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BlueTable',
            fields=[
                ('blueid', models.IntegerField(db_column='blueID', primary_key=True, serialize=False)),
                ('blueimage', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'blue_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BrownTable',
            fields=[
                ('brownid', models.IntegerField(db_column='brownID', primary_key=True, serialize=False)),
                ('brownimage', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'brown_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ColorTable',
            fields=[
                ('colorid', models.AutoField(db_column='colorID', primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'color_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerTable',
            fields=[
                ('customerid', models.IntegerField(db_column='CustomerID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=45)),
                ('address', models.CharField(db_column='Address', max_length=45)),
                ('contactno_field', models.CharField(db_column='ContactNo.', max_length=45)),
            ],
            options={
                'db_table': 'customer_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeliveryTable',
            fields=[
                ('deliveryid', models.IntegerField(db_column='deliveryID', primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.IntegerField()),
            ],
            options={
                'db_table': 'delivery_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrayTable',
            fields=[
                ('grayid', models.IntegerField(db_column='grayID', primary_key=True, serialize=False)),
                ('grayimage', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'gray_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonthyreportTable',
            fields=[
                ('monthlyreportid', models.IntegerField(db_column='monthlyreportID', primary_key=True, serialize=False)),
                ('days', models.IntegerField()),
                ('weeks', models.IntegerField()),
                ('months', models.IntegerField()),
                ('revenue', models.IntegerField()),
            ],
            options={
                'db_table': 'monthyreport_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrangeTable',
            fields=[
                ('orangeid', models.IntegerField(db_column='orangeID', primary_key=True, serialize=False)),
                ('orangeimage', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'orange_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderTable',
            fields=[
                ('orderid', models.IntegerField(db_column='orderID', primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'order_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PriceTable',
            fields=[
                ('priceid', models.IntegerField(db_column='priceID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'price_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('productid', models.IntegerField(db_column='productID', primary_key=True, serialize=False)),
                ('productname', models.CharField(max_length=45)),
                ('productimage', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'product_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RedTable',
            fields=[
                ('redid', models.IntegerField(db_column='redID', primary_key=True, serialize=False)),
                ('redimage', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'red_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=99)),
                ('lname', models.CharField(max_length=99)),
                ('username', models.CharField(max_length=99)),
                ('password', models.CharField(max_length=99)),
            ],
            options={
                'db_table': 'register',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SalesTable',
            fields=[
                ('salesid', models.IntegerField(db_column='salesID', primary_key=True, serialize=False)),
                ('total_price', models.IntegerField()),
                ('sales_date', models.DateField(blank=True, null=True)),
                ('sales_time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sales_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SizeTable',
            fields=[
                ('sizeid', models.CharField(db_column='sizeID', max_length=45, primary_key=True, serialize=False)),
                ('size', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'size_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StatusTable',
            fields=[
                ('statusid', models.IntegerField(db_column='statusID', primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'status_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WhiteTable',
            fields=[
                ('whiteid', models.IntegerField(db_column='whiteID', primary_key=True, serialize=False)),
                ('whiteimage', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'white_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YellowTable',
            fields=[
                ('yellowid', models.IntegerField(db_column='yellowID', primary_key=True, serialize=False)),
                ('yellowimage', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'yellow_table',
                'managed': False,
            },
        ),
    ]
