# Generated by Django 4.2.20 on 2025-09-22 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_dc', '0004_salesaddresstable_delete_customeraddresstable_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salestable',
            options={},
        ),
    ]
